version: '3'
services:
  jupyter-datascience_notebook:
#    networks: 
#      webpage-archer:
#        ipv4_address: 10.254.249.2
    build:
      context: ./jupyter-datascience_notebook
      dockerfile: Dockerfile
    image: jupyter/datascience-notebook:live
    restart: always
    privileged: true
    container_name: jupyter-datascience_notebook
    ports:
      - '7500:8888'
    environment:
      TZ: Asia/Tokyo
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    volumes:
      - /home/nibiohnproj9/chikamori/data:/home/nibiohnproj9/chikamori/data
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

