FROM jupyter/datascience-notebook:latest

MAINTAINER Chikamori Hisafumi

USER root

# first process

RUN apt-get update

# git

RUN apt-get install git

RUN git config --global user.email "chikamori@nibiohn.go.jp"
RUN git config --global user.name "Hisafumi Chikamori"

#RUN pip install opencv-python
#RUN pip install pypdf
#RUN pip install --upgrade --force-reinstall reportlab



